import { FormEvent, useEffect, useState } from 'react'
import { Plus, Search, PhoneCall, Mail, MessageCircle, UsersRound, Presentation, Linkedin, ListTodo, StickyNote } from 'lucide-react'
import PageHeader from '../components/PageHeader'
import Modal from '../components/Modal'
import Loading from '../components/Loading'
import EmptyState from '../components/EmptyState'
import { Field, Input, Select, Textarea } from '../components/FormFields'
import { useTableData } from '../hooks/useTableData'
import { supabase } from '../lib/supabase'
import { dateLabel, titleCase } from '../lib/format'

const icons:any={call:PhoneCall,email:Mail,whatsapp:MessageCircle,meeting:UsersRound,demo:Presentation,linkedin:Linkedin,follow_up:ListTodo,note:StickyNote}
const blank={company_id:'',contact_id:'',deal_id:'',activity_type:'call',subject:'',details:'',activity_at:new Date().toISOString().slice(0,16),next_follow_up:''}
export default function ActivitiesPage(){
 const {data,loading,refresh}=useTableData<any>('activity_overview','*','activity_at');const [companies,setCompanies]=useState<any[]>([]);const [contacts,setContacts]=useState<any[]>([]);const [deals,setDeals]=useState<any[]>([]);const [q,setQ]=useState('');const [open,setOpen]=useState(false);const [form,setForm]=useState<any>(blank);const [error,setError]=useState('');const [saving,setSaving]=useState(false)
 useEffect(()=>{Promise.all([supabase.from('my_company_overview').select('company_id,company_name').order('company_name'),supabase.from('contact_overview').select('id,full_name,company_id'),supabase.from('deal_overview').select('id,name,company_id')]).then(([a,b,c])=>{setCompanies(a.data||[]);setContacts(b.data||[]);setDeals(c.data||[])})},[])
 const submit=async(e:FormEvent)=>{e.preventDefault();setSaving(true);setError('');const payload={...form,contact_id:form.contact_id||null,deal_id:form.deal_id||null,next_follow_up:form.next_follow_up||null,activity_at:new Date(form.activity_at).toISOString()};const {error:e1}=await supabase.from('activities').insert(payload);if(e1)setError(e1.message);else{setOpen(false);setForm(blank);await refresh()}setSaving(false)}
 const rows=data.filter(r=>[r.subject,r.company_name,r.contact_name,r.activity_type].join(' ').toLowerCase().includes(q.toLowerCase()))
 return <><PageHeader title="Activities & Follow-ups" subtitle="Keep calls, emails, meetings, demos and next actions private inside the reseller workspace." actions={<button className="btn primary" onClick={()=>setOpen(true)}><Plus size={18}/>Log activity</button>}/><div className="toolbar"><div className="search-box"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search activities…"/></div></div>{loading?<Loading/>:rows.length?<div className="activity-list">{rows.map(r=>{const Icon=icons[r.activity_type]||StickyNote;return <article className="activity-row" key={r.id}><div className="activity-icon"><Icon size={17}/></div><div className="activity-main"><div><strong>{r.subject}</strong><span>{titleCase(r.activity_type)}</span></div><p>{r.company_name}{r.contact_name?` · ${r.contact_name}`:''}</p>{r.details&&<small>{r.details}</small>}</div><div className="activity-date"><strong>{dateLabel(r.activity_at)}</strong>{r.next_follow_up&&<span>Follow-up {dateLabel(r.next_follow_up)}</span>}</div></article>})}</div>:<EmptyState title="No activities logged yet"/>}
 <Modal open={open} onClose={()=>setOpen(false)} title="Log activity"><form className="form-grid" onSubmit={submit}><Field label="Company" full><Select required value={form.company_id} onChange={e=>setForm({...form,company_id:e.target.value,contact_id:'',deal_id:''})}><option value="">Select company</option>{companies.map(c=><option key={c.company_id} value={c.company_id}>{c.company_name}</option>)}</Select></Field><Field label="Type"><Select value={form.activity_type} onChange={e=>setForm({...form,activity_type:e.target.value})}>{Object.keys(icons).map(v=><option key={v} value={v}>{titleCase(v)}</option>)}</Select></Field><Field label="Activity time"><Input type="datetime-local" required value={form.activity_at} onChange={e=>setForm({...form,activity_at:e.target.value})}/></Field><Field label="Contact"><Select value={form.contact_id} onChange={e=>setForm({...form,contact_id:e.target.value})}><option value="">No contact</option>{contacts.filter(c=>!form.company_id||c.company_id===form.company_id).map(c=><option key={c.id} value={c.id}>{c.full_name}</option>)}</Select></Field><Field label="Deal"><Select value={form.deal_id} onChange={e=>setForm({...form,deal_id:e.target.value})}><option value="">No deal</option>{deals.filter(d=>!form.company_id||d.company_id===form.company_id).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</Select></Field><Field label="Subject" full><Input required value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/></Field><Field label="Details" full><Textarea rows={3} value={form.details} onChange={e=>setForm({...form,details:e.target.value})}/></Field><Field label="Next follow-up" full><Input type="datetime-local" value={form.next_follow_up} onChange={e=>setForm({...form,next_follow_up:e.target.value})}/></Field>{error&&<div className="form-error field-full">{error}</div>}<div className="form-actions field-full"><button type="button" className="btn secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn primary" disabled={saving}>Save activity</button></div></form></Modal></>
}
