import { FormEvent, useEffect, useState } from 'react'
import { Plus, Search, Mail, Phone } from 'lucide-react'
import PageHeader from '../components/PageHeader'
import Modal from '../components/Modal'
import Loading from '../components/Loading'
import EmptyState from '../components/EmptyState'
import { Field, Input, Select, Textarea } from '../components/FormFields'
import { useTableData } from '../hooks/useTableData'
import { supabase } from '../lib/supabase'

const blank={company_id:'',first_name:'',last_name:'',job_title:'',email:'',phone:'',linkedin_url:'',is_decision_maker:false,notes:''}
export default function ContactsPage(){
 const {data,loading,refresh}=useTableData<any>('contact_overview','*','created_at'); const [companies,setCompanies]=useState<any[]>([]); const [q,setQ]=useState(''); const [open,setOpen]=useState(false); const [form,setForm]=useState<any>(blank); const [saving,setSaving]=useState(false); const [error,setError]=useState('')
 useEffect(()=>{supabase.from('my_company_overview').select('company_id,company_name').order('company_name').then(({data})=>setCompanies(data||[]))},[])
 const submit=async(e:FormEvent)=>{e.preventDefault();setSaving(true);setError('');const {error:e1}=await supabase.from('contacts').insert({...form,is_decision_maker:!!form.is_decision_maker});if(e1)setError(e1.message);else{setOpen(false);setForm(blank);await refresh()}setSaving(false)}
 const rows=data.filter(r=>[r.full_name,r.company_name,r.job_title,r.email].join(' ').toLowerCase().includes(q.toLowerCase()))
 return <><PageHeader title="Contacts" subtitle="Private people and relationship details visible only inside your reseller workspace." actions={<button className="btn primary" onClick={()=>setOpen(true)}><Plus size={18}/>Add contact</button>}/><div className="toolbar"><div className="search-box"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search contacts…"/></div></div>{loading?<Loading/>:rows.length?<div className="contacts-grid">{rows.map(r=><article className="contact-card" key={r.id}><div className="contact-avatar">{(r.first_name||'?')[0]}{(r.last_name||'')[0]}</div><div className="contact-body"><h3>{r.full_name}</h3><p>{r.job_title||'Contact'} · {r.company_name}</p><div className="contact-links">{r.email&&<a href={`mailto:${r.email}`}><Mail size={15}/>{r.email}</a>}{r.phone&&<a href={`tel:${r.phone}`}><Phone size={15}/>{r.phone}</a>}</div>{r.is_decision_maker&&<span className="mini-tag">Decision maker</span>}</div></article>)}</div>:<EmptyState title="No private contacts yet"/>}
 <Modal open={open} onClose={()=>setOpen(false)} title="Add contact"><form className="form-grid" onSubmit={submit}><Field label="Company" full><Select required value={form.company_id} onChange={e=>setForm({...form,company_id:e.target.value})}><option value="">Select company</option>{companies.map(c=><option key={c.company_id} value={c.company_id}>{c.company_name}</option>)}</Select></Field><Field label="First name"><Input required value={form.first_name} onChange={e=>setForm({...form,first_name:e.target.value})}/></Field><Field label="Last name"><Input value={form.last_name} onChange={e=>setForm({...form,last_name:e.target.value})}/></Field><Field label="Job title"><Input value={form.job_title} onChange={e=>setForm({...form,job_title:e.target.value})}/></Field><Field label="Email"><Input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label="Phone"><Input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field><Field label="LinkedIn"><Input value={form.linkedin_url} onChange={e=>setForm({...form,linkedin_url:e.target.value})}/></Field><Field label="Decision maker"><Select value={form.is_decision_maker?'yes':'no'} onChange={e=>setForm({...form,is_decision_maker:e.target.value==='yes'})}><option value="no">No</option><option value="yes">Yes</option></Select></Field><Field label="Notes" full><Textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field>{error&&<div className="form-error field-full">{error}</div>}<div className="form-actions field-full"><button type="button" className="btn secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn primary" disabled={saving}>Save contact</button></div></form></Modal></>
}
