import { FormEvent, useEffect, useMemo, useState } from 'react'
import { Plus } from 'lucide-react'
import PageHeader from '../components/PageHeader'
import Modal from '../components/Modal'
import Loading from '../components/Loading'
import { Field, Input, Select, Textarea } from '../components/FormFields'
import { useTableData } from '../hooks/useTableData'
import { supabase } from '../lib/supabase'
import { money, dateLabel, titleCase } from '../lib/format'

const stages=['discovery','qualified','demo','proposal','negotiation','won','lost']
const blank={company_id:'',contact_id:'',name:'',stage:'discovery',value:'',probability:20,expected_close_date:'',product_name:'',location_count:1,next_action:'',notes:''}
export default function DealsPage(){
 const {data,loading,refresh}=useTableData<any>('deal_overview','*','created_at'); const [companies,setCompanies]=useState<any[]>([]); const [contacts,setContacts]=useState<any[]>([]); const [open,setOpen]=useState(false); const [form,setForm]=useState<any>(blank); const [saving,setSaving]=useState(false); const [error,setError]=useState('')
 useEffect(()=>{Promise.all([supabase.from('my_company_overview').select('company_id,company_name').order('company_name'),supabase.from('contact_overview').select('id,full_name,company_id').order('full_name')]).then(([c,p])=>{setCompanies(c.data||[]);setContacts(p.data||[])})},[])
 const grouped=useMemo(()=>Object.fromEntries(stages.map(s=>[s,data.filter(r=>r.stage===s)])),[data])
 const submit=async(e:FormEvent)=>{e.preventDefault();setSaving(true);setError('');const {error:e1}=await supabase.from('deals').insert({...form,contact_id:form.contact_id||null,value:Number(form.value||0),probability:Number(form.probability||0),location_count:Number(form.location_count||1),expected_close_date:form.expected_close_date||null});if(e1)setError(e1.message);else{setOpen(false);setForm(blank);await refresh()}setSaving(false)}
 const move=async(id:string,stage:string)=>{await supabase.from('deals').update({stage}).eq('id',id);await refresh()}
 return <><PageHeader title="Deals Pipeline" subtitle="Manage private reseller opportunities from discovery through win or loss." actions={<button className="btn primary" onClick={()=>setOpen(true)}><Plus size={18}/>New deal</button>}/>{loading?<Loading/>:<div className="kanban">{stages.map(stage=><section className="kanban-col" key={stage}><header><div><strong>{titleCase(stage)}</strong><span>{grouped[stage].length}</span></div><small>{money(grouped[stage].reduce((s:number,r:any)=>s+Number(r.value||0),0))}</small></header><div className="kanban-stack">{grouped[stage].map((r:any)=><article className="deal-card" key={r.id}><h3>{r.name}</h3><p>{r.company_name}</p><div className="deal-value">{money(r.value,r.currency)}<span>{r.probability}%</span></div><div className="deal-meta"><span>{r.location_count||1} location(s)</span><span>{dateLabel(r.expected_close_date)}</span></div><select className="stage-select" value={r.stage} onChange={e=>move(r.id,e.target.value)}>{stages.map(s=><option key={s} value={s}>{titleCase(s)}</option>)}</select></article>)}{!grouped[stage].length&&<div className="kanban-empty">No deals</div>}</div></section>)}</div>}
 <Modal open={open} onClose={()=>setOpen(false)} title="Create deal" wide><form className="form-grid" onSubmit={submit}><Field label="Company"><Select required value={form.company_id} onChange={e=>setForm({...form,company_id:e.target.value,contact_id:''})}><option value="">Select company</option>{companies.map(c=><option key={c.company_id} value={c.company_id}>{c.company_name}</option>)}</Select></Field><Field label="Contact"><Select value={form.contact_id} onChange={e=>setForm({...form,contact_id:e.target.value})}><option value="">No contact</option>{contacts.filter(c=>!form.company_id||c.company_id===form.company_id).map(c=><option key={c.id} value={c.id}>{c.full_name}</option>)}</Select></Field><Field label="Deal name" full><Input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Stage"><Select value={form.stage} onChange={e=>setForm({...form,stage:e.target.value})}>{stages.map(s=><option key={s} value={s}>{titleCase(s)}</option>)}</Select></Field><Field label="Probability %"><Input type="number" min="0" max="100" value={form.probability} onChange={e=>setForm({...form,probability:e.target.value})}/></Field><Field label="Deal value"><Input type="number" min="0" step="0.01" value={form.value} onChange={e=>setForm({...form,value:e.target.value})}/></Field><Field label="Expected close"><Input type="date" value={form.expected_close_date} onChange={e=>setForm({...form,expected_close_date:e.target.value})}/></Field><Field label="Product"><Input value={form.product_name} onChange={e=>setForm({...form,product_name:e.target.value})}/></Field><Field label="Locations"><Input type="number" min="1" value={form.location_count} onChange={e=>setForm({...form,location_count:e.target.value})}/></Field><Field label="Next action" full><Input value={form.next_action} onChange={e=>setForm({...form,next_action:e.target.value})}/></Field><Field label="Notes" full><Textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field>{error&&<div className="form-error field-full">{error}</div>}<div className="form-actions field-full"><button type="button" className="btn secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn primary" disabled={saving}>Create deal</button></div></form></Modal></>
}
