import { FormEvent, useState } from 'react'
import { Search, WalletCards, Eye } from 'lucide-react'
import PageHeader from '../components/PageHeader'
import Modal from '../components/Modal'
import Loading from '../components/Loading'
import EmptyState from '../components/EmptyState'
import StatusBadge from '../components/StatusBadge'
import { Field, Input, Select } from '../components/FormFields'
import { useTableData } from '../hooks/useTableData'
import { supabase } from '../lib/supabase'
import { dateLabel, money } from '../lib/format'
import { useAuth } from '../contexts/AuthContext'

export default function InvoicesPage(){
 const {isAdmin}=useAuth(); const {data,loading,refresh}=useTableData<any>('invoice_financials','*','issued_at'); const [q,setQ]=useState(''); const [selected,setSelected]=useState<any>(null); const [payOpen,setPayOpen]=useState(false); const [form,setForm]=useState<any>({amount:'',paid_at:new Date().toISOString().slice(0,10),method:'bank_transfer',reference:''}); const [saving,setSaving]=useState(false); const [error,setError]=useState('')
 const rows=data.filter(r=>[r.invoice_number,r.reseller_name,r.client_name,r.status].join(' ').toLowerCase().includes(q.toLowerCase()))
 const startPayment=(r:any)=>{setSelected(r);setForm({amount:r.balance,paid_at:new Date().toISOString().slice(0,10),method:'bank_transfer',reference:''});setError('');setPayOpen(true)}
 const record=async(e:FormEvent)=>{e.preventDefault();setSaving(true);setError('');const {error:e1}=await supabase.rpc('record_invoice_payment',{p_invoice_id:selected.id,p_amount:Number(form.amount),p_paid_at:form.paid_at,p_method:form.method,p_reference:form.reference||null});if(e1)setError(e1.message);else{setPayOpen(false);await refresh()}setSaving(false)}
 return <><PageHeader title="Invoices" subtitle="Invoices are issued to the reseller and can reference the end client, location and originating request or renewal."/><div className="toolbar"><div className="search-box"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search invoices…"/></div></div>{loading?<Loading/>:rows.length?<div className="panel table-panel"><div className="table-wrap"><table><thead><tr><th>Invoice</th><th>Reseller / Client</th><th>Issued / Due</th><th>Total</th><th>Paid</th><th>Balance</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.invoice_number}</strong><small>{r.reference||'—'}</small></td><td><strong>{r.reseller_name}</strong><small>{r.client_name||r.location_name||'Direct reseller invoice'}</small></td><td>{dateLabel(r.issued_at)}<small>Due {dateLabel(r.due_date)}</small></td><td>{money(r.total,r.currency)}</td><td>{money(r.paid_total,r.currency)}</td><td><strong>{money(r.balance,r.currency)}</strong></td><td><StatusBadge value={r.financial_status}/></td><td className="actions-cell">{isAdmin&&Number(r.balance)>0&&r.status==='issued'&&<button className="btn small primary" onClick={()=>startPayment(r)}><WalletCards size={15}/>Record payment</button>}</td></tr>)}</tbody></table></div></div>:<EmptyState title="No invoices yet"/>}
 <Modal open={payOpen} onClose={()=>setPayOpen(false)} title={`Record payment · ${selected?.invoice_number||''}`}><form className="form-grid" onSubmit={record}><div className="payment-summary field-full"><span>Outstanding balance</span><strong>{money(selected?.balance,selected?.currency)}</strong></div><Field label="Amount received" full><Input type="number" min="0.01" max={selected?.balance} step="0.01" required value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></Field><Field label="Payment date"><Input type="date" required value={form.paid_at} onChange={e=>setForm({...form,paid_at:e.target.value})}/></Field><Field label="Method"><Select value={form.method} onChange={e=>setForm({...form,method:e.target.value})}><option value="bank_transfer">Bank transfer</option><option value="cash">Cash</option><option value="card">Card</option><option value="cheque">Cheque</option><option value="other">Other</option></Select></Field><Field label="Bank / transfer reference" full><Input value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/></Field>{error&&<div className="form-error field-full">{error}</div>}<div className="form-actions field-full"><button type="button" className="btn secondary" onClick={()=>setPayOpen(false)}>Cancel</button><button className="btn primary" disabled={saving}>{saving?'Recording…':'Record & issue receipt'}</button></div></form></Modal></>
}
