import { FormEvent, useEffect, useState } from 'react'
import { Plus, Search } from 'lucide-react'
import PageHeader from '../components/PageHeader'
import Modal from '../components/Modal'
import Loading from '../components/Loading'
import EmptyState from '../components/EmptyState'
import StatusBadge from '../components/StatusBadge'
import { Field, Input, Select, Textarea } from '../components/FormFields'
import { useTableData } from '../hooks/useTableData'
import { supabase } from '../lib/supabase'
import { money, dateLabel, titleCase } from '../lib/format'

const blank={company_id:'',contact_id:'',title:'',source:'',status:'new',priority:'medium',estimated_value:'',next_follow_up:'',notes:''}
export default function LeadsPage(){
 const {data,loading,refresh}=useTableData<any>('lead_overview','*','created_at'); const [companies,setCompanies]=useState<any[]>([]); const [contacts,setContacts]=useState<any[]>([]); const [q,setQ]=useState(''); const [open,setOpen]=useState(false); const [form,setForm]=useState<any>(blank); const [saving,setSaving]=useState(false); const [error,setError]=useState('')
 useEffect(()=>{Promise.all([supabase.from('my_company_overview').select('company_id,company_name').order('company_name'),supabase.from('contact_overview').select('id,full_name,company_id').order('full_name')]).then(([c,p])=>{setCompanies(c.data||[]);setContacts(p.data||[])})},[])
 const submit=async(e:FormEvent)=>{e.preventDefault();setSaving(true);setError('');const payload={...form,contact_id:form.contact_id||null,estimated_value:form.estimated_value?Number(form.estimated_value):0,next_follow_up:form.next_follow_up||null};const {error:e1}=await supabase.from('leads').insert(payload);if(e1)setError(e1.message);else{setOpen(false);setForm(blank);await refresh()}setSaving(false)}
 const rows=data.filter(r=>[r.title,r.company_name,r.status,r.source].join(' ').toLowerCase().includes(q.toLowerCase()))
 return <><PageHeader title="Leads" subtitle="Track early opportunities, qualification and next follow-up." actions={<button className="btn primary" onClick={()=>setOpen(true)}><Plus size={18}/>New lead</button>}/><div className="toolbar"><div className="search-box"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search leads…"/></div></div>{loading?<Loading/>:rows.length?<div className="panel table-panel"><div className="table-wrap"><table><thead><tr><th>Lead</th><th>Status</th><th>Priority</th><th>Value</th><th>Follow-up</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.title}</strong><small>{r.company_name}{r.contact_name?` · ${r.contact_name}`:''}</small></td><td><StatusBadge value={r.status}/></td><td>{titleCase(r.priority)}</td><td>{money(r.estimated_value,r.currency)}</td><td>{dateLabel(r.next_follow_up)}</td></tr>)}</tbody></table></div></div>:<EmptyState title="No leads yet"/>}
 <Modal open={open} onClose={()=>setOpen(false)} title="Create lead"><form className="form-grid" onSubmit={submit}><Field label="Company" full><Select required value={form.company_id} onChange={e=>setForm({...form,company_id:e.target.value,contact_id:''})}><option value="">Select company</option>{companies.map(c=><option key={c.company_id} value={c.company_id}>{c.company_name}</option>)}</Select></Field><Field label="Lead title" full><Input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="e.g. Multi-location rollout opportunity"/></Field><Field label="Contact"><Select value={form.contact_id} onChange={e=>setForm({...form,contact_id:e.target.value})}><option value="">No contact selected</option>{contacts.filter(c=>!form.company_id||c.company_id===form.company_id).map(c=><option key={c.id} value={c.id}>{c.full_name}</option>)}</Select></Field><Field label="Source"><Input value={form.source} onChange={e=>setForm({...form,source:e.target.value})} placeholder="Referral, LinkedIn, event…"/></Field><Field label="Status"><Select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{['new','contacting','contacted','qualified','converted','disqualified'].map(v=><option key={v} value={v}>{titleCase(v)}</option>)}</Select></Field><Field label="Priority"><Select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{['low','medium','high','urgent'].map(v=><option key={v} value={v}>{titleCase(v)}</option>)}</Select></Field><Field label="Estimated value"><Input type="number" min="0" step="0.01" value={form.estimated_value} onChange={e=>setForm({...form,estimated_value:e.target.value})}/></Field><Field label="Next follow-up"><Input type="date" value={form.next_follow_up} onChange={e=>setForm({...form,next_follow_up:e.target.value})}/></Field><Field label="Notes" full><Textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field>{error&&<div className="form-error field-full">{error}</div>}<div className="form-actions field-full"><button type="button" className="btn secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn primary" disabled={saving}>Create lead</button></div></form></Modal></>
}
