import { FormEvent, useMemo, useState } from 'react'
import { Network, Search, Users, Store, MapPin, RefreshCw, WalletCards, Plus } from 'lucide-react'
import PageHeader from '../components/PageHeader'
import StatCard from '../components/StatCard'
import Loading from '../components/Loading'
import EmptyState from '../components/EmptyState'
import StatusBadge from '../components/StatusBadge'
import Modal from '../components/Modal'
import { Field, Input, Select } from '../components/FormFields'
import { useTableData } from '../hooks/useTableData'
import { supabase } from '../lib/supabase'
import { money } from '../lib/format'

const blank={code:'',name:'',legal_name:'',country:'',currency:'USD',billing_email:'',payment_term_days:30}
export default function ResellersPage(){
 const {data,loading,refresh}=useTableData<any>('reseller_360','*','name'); const [q,setQ]=useState(''); const [open,setOpen]=useState(false); const [form,setForm]=useState<any>(blank); const [saving,setSaving]=useState(false); const [error,setError]=useState('')
 const rows=useMemo(()=>data.filter(r=>[r.name,r.code,r.country,r.status].join(' ').toLowerCase().includes(q.toLowerCase())),[data,q])
 const active=rows.filter(r=>r.status==='active').length; const clients=rows.reduce((s,r)=>s+Number(r.active_clients||0),0); const locations=rows.reduce((s,r)=>s+Number(r.active_locations||0),0); const outstanding=rows.reduce((s,r)=>s+Number(r.outstanding||0),0)
 const submit=async(e:FormEvent)=>{e.preventDefault();setSaving(true);setError('');const {error:e1}=await supabase.from('resellers').insert({...form,payment_term_days:Number(form.payment_term_days)});if(e1)setError(e1.message);else{setOpen(false);setForm(blank);await refresh()}setSaving(false)}
 return <><PageHeader title="Resellers 360" subtitle="A complete admin view of each reseller’s CRM footprint, active portfolio, renewals and financial position." actions={<button className="btn primary" onClick={()=>setOpen(true)}><Plus size={18}/>Add reseller</button>}/><div className="stats-grid"><StatCard label="Active resellers" value={active} icon={Network}/><StatCard label="Active clients" value={clients} icon={Store}/><StatCard label="Active locations" value={locations} icon={MapPin}/><StatCard label="Outstanding" value={money(outstanding)} icon={WalletCards}/></div><div className="toolbar"><div className="search-box"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search reseller…"/></div></div>{loading?<Loading/>:rows.length?<div className="reseller-grid">{rows.map(r=><article className="reseller-card" key={r.id}><div className="reseller-head"><div className="reseller-avatar">{r.name?.[0]||'R'}</div><div><h3>{r.name}</h3><p>{r.code} · {r.country||'No country'}</p></div><StatusBadge value={r.status}/></div><div className="reseller-metrics"><div><Users size={16}/><span>Companies</span><strong>{r.companies||0}</strong></div><div><Store size={16}/><span>Clients</span><strong>{r.active_clients||0}</strong></div><div><MapPin size={16}/><span>Locations</span><strong>{r.active_locations||0}</strong></div><div><RefreshCw size={16}/><span>Renewals 30d</span><strong>{r.renewals_30d||0}</strong></div></div><div className="reseller-finance"><div><span>Invoiced</span><strong>{money(r.total_invoiced,r.currency)}</strong></div><div><span>Paid</span><strong>{money(r.total_paid,r.currency)}</strong></div><div><span>Outstanding</span><strong>{money(r.outstanding,r.currency)}</strong></div><div><span>Overdue</span><strong className={Number(r.overdue)>0?'danger-text':''}>{money(r.overdue,r.currency)}</strong></div></div></article>)}</div>:<EmptyState title="No resellers configured"/>}
 <Modal open={open} onClose={()=>setOpen(false)} title="Add reseller"><form className="form-grid" onSubmit={submit}><Field label="Code"><Input required value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})} placeholder="RSL-001"/></Field><Field label="Display name"><Input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Legal name" full><Input value={form.legal_name} onChange={e=>setForm({...form,legal_name:e.target.value})}/></Field><Field label="Country"><Input value={form.country} onChange={e=>setForm({...form,country:e.target.value})}/></Field><Field label="Currency"><Select value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}><option>USD</option><option>AED</option><option>SAR</option><option>EUR</option><option>GBP</option></Select></Field><Field label="Billing email"><Input type="email" value={form.billing_email} onChange={e=>setForm({...form,billing_email:e.target.value})}/></Field><Field label="Default payment term"><Select value={form.payment_term_days} onChange={e=>setForm({...form,payment_term_days:e.target.value})}><option value="0">Due immediately</option><option value="7">Net 7</option><option value="14">Net 14</option><option value="21">Net 21</option><option value="30">Net 30</option></Select></Field>{error&&<div className="form-error field-full">{error}</div>}<div className="form-actions field-full"><button type="button" className="btn secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn primary" disabled={saving}>Create reseller</button></div></form></Modal></>
}
